---
title: "EDA for Milestone Medicare Data"
author: "Xilin Chen"
date: "2/24/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,                                     # code
  message = F,
  warning = F,
  error = F,
  comment = NA,
  R.options = list(width = 220),
  dev.args = list(bg = 'transparent'),          # viz
  dev = 'png',
  fig.align = 'center',
  cache = F
  # out.width = '100%',
  # fig.asp = .5,
)      

library(tidyverse)
library(tidyext)
library(kableExtra)
library(icd)
library(data.table)
library(lubridate)

kable_df <- function(..., digits=2) {
  kable(...,digits = digits) %>% 
    kable_styling(full_width = F, latex_options = "hold_position")
}

```

```{r load_data}
load("/Volumes/George_Surgeon_Projects/Milestone_vs_Outcomes/milestone_medicare_pc.rdata")
```


```{r surgeons}
milestone_medicare_pc %>% 
  count(val_yr_practice) %>% 
  kable_df()

milestone_medicare_pc %>% 
  summarise(n_case = n(),
            n_surgeon = length(unique(id_physician_npi)),
            POA_severe_complication_rate = sum(flg_cmp_po_severe_poa)/n_case,
            severe_complication_rate = sum(flg_cmp_po_severe)/n_case,
            POA_any_complication_rate = sum(flg_cmp_po_any_poa)/n_case,
            any_complication_rate = sum(flg_cmp_po_any)/n_case,
            death_rate = sum(flg_death_30d)/n_case,
            readmit = sum(flg_readmit_30d)/n_case,
            reop = sum(flg_util_reop)/n_case) %>% 
  t() %>% 
  kable_df(caption = "Medicare Outcomes Description")

```

# CPT count

```{r CPT}
milestone_medicare_pc %>% 
  count(cpt_cd, sort = T) %>% 
  kable_df()
```


# ICD hospital

```{r icu_hosp}
milestone_medicare_pc %>% 
  count(flg_hosp_ICU_hosp, flg_cmp_po_severe_poa)
```

