---
title: "Milestone Data 101"
author: "Xilin Chen"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,                                     # code
  message = F,
  warning = F,
  error = F,
  comment = NA,
  R.options = list(width = 220),
  dev.args = list(bg = 'transparent'),          # viz
  dev = 'png',
  fig.align = 'center',
  cache = F
  # out.width = '100%',
  # fig.asp = .5,
)    

library(tidyverse)
library(kableExtra)
library(lubridate)


kable_df <- function(..., digits=2) {
  kable(...,digits = digits) %>% 
    kable_styling(full_width = F, latex_options = "hold_position")
}
```

# About this Document

This document explores some basic quality stats for the Milestone data received on Jan 2020.

```{r data_import, cache=TRUE}
load("/Volumes/George_Surgeon_Projects/ACGME_milestone/data/milestone_01_2020.rdata")

glimpse(milestone)
```

# Data

## Person ID and NPI values missingness

```{r NPI}
milestone %>% 
  distinct(NPI, PersonID) %>%
  summarise(n_tot_person = n(), missing_npi = sum(is.na(NPI)), perc_missing_npi = missing_npi/n_tot_person,
            n_missing_personID = sum(is.na(PersonID))) %>% 
  kable_df(caption = "NPI and PersonID")

# milestone %>% 
#   filter(is.na(PersonID)) %>% 
#   glimpse()
```

## Last4SSN

```{r SSN}
numbers_only <- function(x) !grepl("\\D", x)

non_numeric_ssn = milestone %>% 
  filter(!numbers_only(Last4SSN)) %>% 
  distinct(PersonID, NPI, Last4SSN)

non_numeric_ssn %>% 
  head() %>% 
  kable_df(caption = "Example of non_numeric SSN") 

milestone %>% 
  filter(nchar(Last4SSN)<4) %>% 
  distinct(PersonID, NPI, Last4SSN) %>% 
  kable_df(caption = "one person has less than 4 digits of SSN")

```


## Date

some Dates are not dates

```{r birthdate}
milestone %>% 
  distinct(PersonID, NPI, BirthDate) %>% 
  filter(str_detect(BirthDate, "\\*")) %>% 
  head()
```

```{r StartDate}
milestone %>% 
  distinct(PersonID, NPI, StartDate) %>% 
  filter(str_detect(StartDate, "\\*")) %>% 
  head()

```

```{r DegreeDate}
milestone %>% 
  distinct(PersonID, NPI, DegreeDate) %>% 
  filter(str_detect(DegreeDate, "\\*")) %>% 
  head()
```


```{r ExpectedCompletionDate}
milestone %>% 
  distinct(PersonID, NPI, ExpectedCompletionDate) %>% 
  filter(str_detect(ExpectedCompletionDate, "\\*")) %>% 
  head()
```