---
title: "Model Summary for Milestone Ratings vs. Medicare Outcomes"
author: "Xilin Chen"
date: "2/24/2020"
output: 
  pdf_document:
    toc: true
    toc_depth: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,                                     # code
  message = F,
  warning = F,
  error = F,
  comment = NA,
  R.options = list(width = 220),
  dev.args = list(bg = 'transparent'),          # viz
  dev = 'png',
  fig.align = 'center',
  cache = F
  # out.width = '100%',
  # fig.asp = .5,
)      

library(tidyverse)
library(tidyext)
library(kableExtra)
library(glmmTMB)
library(data.table)
library(lubridate)
library(mixedup)

kable_df <- function(..., digits=2) {
  kable(...,digits = digits) %>% 
    kable_styling(full_width = F, latex_options = "hold_position")
}

```

```{r load_data, cache=TRUE}
load("/Volumes/George_Surgeon_Projects/Milestone_vs_Outcomes/milestone_medicare_pc.rdata")
```

# Whole data Description

```{r data_desc}
milestone_medicare_pc %>% 
  summarise(n_case = n(),
            n_surgeon = length(unique(id_physician_npi)),
            POA_severe_complication_rate = sum(flg_cmp_po_severe_poa)/n_case,
            severe_complication_rate = sum(flg_cmp_po_severe)/n_case,
            POA_any_complication_rate = sum(flg_cmp_po_any_poa)/n_case,
            any_complication_rate = sum(flg_cmp_po_any)/n_case,
            death_rate = sum(flg_death_30d)/n_case,
            readmit = sum(flg_readmit_30d)/n_case,
            reop = sum(flg_util_reop)/n_case) %>% 
  t() %>% 
  kable_df(caption = "Medicare Outcomes Description")

```

```{r rating_desc}
milestone_medicare_pc %>% 
  ggplot() +
  geom_bar(aes(x =IntResponseValue_mean)) +
  theme_classic() +
  xlab("Mean Milestone Rating")

milestone_medicare_pc %>% 
  num_by(IntResponseValue_mean) %>% 
  kable_df()
```


```{r load_model, cache=TRUE}
load("/Volumes/George_Surgeon_Projects/Milestone_vs_Outcomes/model/results_tmb.rdata")
```

```{r model }
model = results$flg_cmp_po_severe_poa


```



```{r fe}
# fe 
fe = extract_fixed_effects(model) %>% 
  mutate(OR = exp(value),
         OR_lower = exp(lower_2.5),
         OR_upper = exp(upper_97.5)
         ) %>% 
  select(-z, -se) %>% 
  rename(Estimate = value) 

fe %>% 
  select(term, starts_with('OR'), everything())  %>% 
  kable_df() %>% 
  pack_rows('Milestone Rating', 2, 2) %>% 
  pack_rows('Patient', 3, 9) %>%
  pack_rows('Case', 10, 12)  %>% 
  pack_rows('Hospital',13, 15)
```



